### ISSUE TITLE
Feature request: Make it working with HA7NET devices

### ISSUE THREAD

**Issue by Foxi352** [lrybak/hassio-owserver#13]
Issue moved from https://github.com/lrybak/addon-repository/issues/1#issue-1738507347 as requested:

I have a [HA7NET](https://www.embeddeddatasystems.com/HA7Net--Ethernet-1-Wire-Host-Adapter_p_22.html) 1-wire to ethernet running for a long time. For now owfs is running on separate server and i want to switch to your addon on the HA VM. Sadly it is not possible to configure the device correctly via config UI.

owfs fully supports the HA7NET device. I get it working by doing a `docker exec -it <container-id> /bin/bash` into your addon's container and editing the` /etc/owfs.conf` file. But on every addon restart it is overwriten.

The needed config line in `/etc/owfs.conf` is:
```
server: ha7net = 192.168.2.242
```

But when i enter `ha7net = 192.168.2.242` in the addon's config UI it generates:
```
server: device = ha7net = 192.168.2.242
```

Would it be possible to maybe the user switch in the config between `device`and `ha7net` of just provide an "advanced" option where one can manually edit the config file ?

**Comment by Foxi352** [comment]
Looking at the latest update, it seems like adding this feature should be just adding a 4th device type to the seleciton list  (in addition to fake, ...) of 'ha7net' and an additional parameter for the IP address.

Thank you already in advance for considering this :-) !

**Comment by lrybak** [comment]
Hi Serge @Foxi352, I've added support for ha7net device. However I don't haver such device so I'm not able to verify it.
Would you please to check it on your side?
The change is in BETA repository so far - https://github.com/lrybak/addon-repository-beta/

**Comment by Foxi352** [comment]
Hey @lrybak,
Thanks for your efforts. Good news first: It works. There are some minor cosmetic issues you could improve, but nothing that affects functionality.

After choosing the "ha7net" option, i had to flip the switch to show hidden options to show the ip address field.
I entered the IP address and wanted to save the config and start the add-on. But it complained that i did not choose a mandatory device:

![Screenshot 2023-11-26 at 12 31 58](https://github.com/lrybak/hassio-owserver/assets/5746932/05c70573-1e04-4361-941b-675e91d5b2d1)
So after choosing whatever device, it successfully saved, started the add-on, and worked out of the box.
Here is the generated config, which is correct:
![Screenshot 2023-11-26 at 13 13 58](https://github.com/lrybak/hassio-owserver/assets/5746932/27134c4b-7d1d-4647-9e47-a7b77d9b2498)

**Comment by lrybak** [comment]
Thanks for your feedback and glad it's working. "Show unused optional configuration options" relates to those options with no default values and I see no sense to adding default value like localhost for that field (ha7net_server) to prevent that behaviour.
I know as well that "glitch" with device selector. Unfortunately the mechanism used to setup configuration options is not ideal. I can't setup validator like: device is not required if you select ha7 but is required in case you selected usb/i2c. 
For your case you can select any device. It doesn't really matter. The logic used to create config file on runtime simply skips that device you select.
I will publish that feature in stable release today.
