### ISSUE TITLE
Feature request: Possibility to bind owfs port to localhost

### ISSUE THREAD

**Issue by Foxi352** [lrybak/hassio-owserver#14]
Correct me if i'm wrong. But currently one cannot bind the owfs port to HAOS.
That means that the 1-wire integration needs the addon's hostname to connect, which is indeed reflected in the doc.
But the hostname changes, afaik, whenever the addon container is restarted, for example by a HAOS reboot.
This always breaks the 1-wire integration. 

Maybe add the possibility in the addon config to bind the container port to a localhost port, as many other addon's do.
That way the 1-wire integration could use localhost as server and entities will never break and have to be redone.

**Comment by lrybak** [comment]
As far as I know the hostname of the addon is generated based on the repository url, see here:

https://developers.home-assistant.io/docs/add-ons/communication/
https://github.com/home-assistant/supervisor/blob/587047f9d648b8491dc8eef17dc6777f81938bfd/hassio/addons/utils.py#L17

So it shouldn't change if the repo name remain the same.

Btw. I started to work on the HA7NET support #13 but I'm quite busy this and next week so hopefully I will be able to finish that somewhere July

**Comment by Foxi352** [comment]
Seems that you're right. I restarted and hostname was the same. Although i am sure that it changed once in the past because integration had another hostname than addon. But anyways, seems good.

The only advantage that i see, giving the user the option to bind the ports on the host, is that another client app could consume / connect to owfs. But i have no use case for this scenario, so all good for me now :-)

Thanks for your work. I can workaround #13 editing the config file manually after a restart. There are not many restarts, so no hurry...
