### ISSUE TITLE
Access the Webinterface with RESTful Sensor

### ISSUE THREAD

**Issue by panzaeron** [lrybak/hassio-owserver#15]
Hello,

I have a 1-wire sensor (DS2450) that is not supported by the Home Assistant 1-wire integration. As a workaround, I would like to read out the sensor page in the web interface with the RESTful sensor. 

Is there a way to parse the sensor page with the RESTful API? 
All my attempts have mostly failed with an authorisation error.

Edit:
After some research, this will now be a feature request. It would be useful if the 1-Wire web interface is not only accessible via INGRESS, but also via port 3001 outside Home Assistant.

**Comment by lrybak** [comment]
@panzaeron: Not sure if exposing web ui outside Home Assistant for latter scraping it is a good idea. You can probably try to solve that by reading sensor over owfs protocol via pyownet with: https://github.com/custom-components/pyscript or https://appdaemon.readthedocs.io/en/latest/ however I have zero experience with those tools so it's rather my guessing.

@epenet that's the way how it should be resolved properly.
