### ISSUE TITLE
Unknown error while adding 1-wire integration

### ISSUE THREAD

**Issue by HynekPetrak** [lrybak/hassio-owserver#18]
Hi Lukas, great effort, thank you!

Could you help me, how to debug below situation. Your add-on seems to be running fine, the web interface is showing the sensors:
![image](https://github.com/lrybak/hassio-owserver/assets/8593983/d761a7c0-c15e-480c-ab74-8346db44ad4e)

however when I attempt to add the 1-wire integration, I get an error with not much info:

![image](https://github.com/lrybak/hassio-owserver/assets/8593983/0c9f493a-6538-47fb-b151-fe433d0db814)

**Comment by HynekPetrak** [comment]
in the ha.log I get this:

![image](https://github.com/lrybak/hassio-owserver/assets/8593983/7c889823-af24-4640-b1bb-340ac1155f45)

**Comment by HynekPetrak** [comment]
further investigating it seems the owserver is crashing and restarting every time I access a sensor via web interface ....

![image](https://github.com/lrybak/hassio-owserver/assets/8593983/e655df5d-20b4-4019-b812-c534ffb905a8)

**Comment by lrybak** [comment]
Hello Hynek,
Can you post screenshot of the addon configuration page?

**Comment by lrybak** [comment]
I think you're running debug mode which is only usefull for the debuging purposes. Try to turn the debug off and then add HomeAssistant integration. Hope that helps
