### ISSUE TITLE
ingress link not working

### ISSUE THREAD

**Issue by sipodd** [lrybak/hassio-owserver#2]
supervisor log:
[supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.5:8099 ssl:default [Connect call failed ('172.30.33.5', 8099)]

response when open Userinterface: 502: Bad Gateway

config:
owhttpd: true
device: ' /dev/ttyAMA0'

Addon Log:
-----------------------------------------------------------
 Add-on: owserver (1-Wire)
 onewire server to read 1-Wire devices
-----------------------------------------------------------
 Add-on version: 0.2.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 6.2  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.8.8
 Home Assistant Supervisor: 2021.06.8
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] owserver.sh: executing... 
[14:05:06] INFO: Configuring  /dev/ttyAMA0 device
[cont-init.d] owserver.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[14:05:06] INFO: Starting owserver...
[14:05:06] INFO: Starting owhttpd...

**Comment by lrybak** [comment]
It looks that you have typo in your configuration. Space between ' and /
device: ' /dev/ttyAMA0'

Check your configuration and try again.
You van start addon with random devices just for testing purpose. To do that leave device parameter empty - device: ''

**Comment by sipodd** [comment]
> It looks that you have typo in your configuration. Space between ' and /
> device: ' /dev/ttyAMA0'
> 
> Check your configuration and try again.
> You van start addon with random devices just for testing purpose. To do that leave device parameter empty - device: ''

Good eye for the typo ;-)
But even with the random device (log names it fake device) I'll get the 502.
After restart of the add on or the whole raspberry.

**Comment by lrybak** [comment]
Can you verify with the latest version 0.2.1 whether the issue still exists?

**Comment by sipodd** [comment]
Hi Irybak, thanks for reaching out. 
I can confirm that it is working with the fake device now, so the issue is solved from my perspective.

I still can not connect my 1wire USB Dongle to the OWServer, but that is related to HA as it doesn't detect the device.

Thanks! :-)

**Comment by lrybak** [comment]
Try to buy the one mentioned on project site. Very reliable and cheap device (around 20EUR). I'm personally using it since 6 or 7 years.
