### ISSUE TITLE
owserver for two USB DS9490 devices

### ISSUE THREAD

**Issue by ArtGudvin** [lrybak/hassio-owserver#22]
Good afternoon. I want to run owserver for two USB DS9490 devices. In the Home assistant add-on configuration, I must select one device, so I only have one DS9490 running OWserver. Tell me how can I run owserver for two USB DS9490 devices?

**Comment by dim6003** [comment]
Hi same issue here, but with 2 "Ha7net" devices. Also opened an issue for that case....
Got any solution on your case?

**Comment by szczukot** [comment]
I have exactly this same problem. How add 2x DS9490?

**Comment by lrybak** [comment]
Hi guys, as far as I know that't not supported to run another instance of the same addon, but I think there is a workaround to do so.
Please install addon from my beta channel. That will give you basically another instance of addon you can configure with another device. 
It might be not so stable but there are not so many changes so we can call it 'pretty stable' ;-)

https://github.com/lrybak/addon-repository-beta

**Comment by dim6003** [comment]
No way to get multiple entries in the yaml configuration?

**Comment by lrybak** [comment]
It’s possible to define multiple devices in owfs, but this requires modifying how the addon is configured in Home Assistant. Users should specify the configuration directly in YAML, rather than using the GUI. 
I have to think about it, but anyway I have very limited in time until end of November, so if it's important to you please follow the workaround.

**Comment by szczukot** [comment]
But how can I add two devices in yaml? 
I can't do it after a space or by giving the device line twice.

**Comment by lrybak** [comment]
Just install beta addon and configure it separatelly. 

In future version I will make it possible to add more devices to single addon instance.

**Comment by dim6003** [comment]
If I can be of any help, by sharing access to my devices, beta testing, or what ever. Programmer background (python, bash, yaml, sql ok, c-java-pascal-asm many years ago, ...)

**Comment by lrybak** [comment]
Perfect I will let you know 😃

**Comment by lrybak** [comment]
I was able to make some time and make changes in the addon
@dim6003 would you please to check if it works for you with two devices?

You can find the change in edge channel, frankly I didn't spend much time yet to test it, please do so and share your thoughts. Thanks

https://github.com/lrybak/addon-repository-edge

**Comment by dim6003** [comment]
I'll do, have some time today and tomorrow. Will tell you.
Any special recommendations (debug mode for logs,. ..)?

Le 29 octobre 2024 00:21:20 GMT+01:00, "Łukasz Rybak" ***@***.***> a écrit :

**Comment by lrybak** [comment]
Just read the documentation how to configure devices, configure and test it. Meanwhile I will do the same on my own however I have just one device so will use some fake one to verify that.
If documentation will not be clear enough please let me know.

**Comment by lrybak** [comment]
Try to run with debug mode and post the logs

**Comment by dim6003** [comment]
`DEBUG:` ow_regex.c:(24) Reg Ex expression <^all$> compiled to 0x7fc753801b20
  DEBUG: ow_regex.c:(24) Reg Ex expression <^scan$> compiled to 0x7fc753801ae0
  DEBUG: ow_regex.c:(24) Reg Ex expression <^\*$> compiled to 0x7fc753801aa0
DEBUG MODE
libow version:
	3.2p4
  DEBUG: ow_regex.c:(24) Reg Ex expression <^[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}$> compiled to 0x7fc753801a60
  DEBUG: ow_regex.c:(24) Reg Ex expression <^-?[[:digit:]]+$> compiled to 0x7fc753801a20
  DEBUG: ow_regex.c:(24) Reg Ex expression <^ *([^ ]+)[ 
]*$> compiled to 0x7fc7538019e0
  DEBUG: ow_regex.c:(24) Reg Ex expression <^ *([^ ]+) *: *([^ ]+)[ 
]*$> compiled to 0x7fc7538019a0
  DEBUG: ow_regex.c:(24) Reg Ex expression <^ *([^ ]+) *: *([^ ]+) *: *([^ ]+)[ 
]*$> compiled to 0x7fc753801960
  DEBUG: ow_regex.c:(53) Not found
  DEBUG: ow_regex.c:(53) Not found
  DEBUG: ow_regex.c:(100) 0: 0->14 found <><192.168.50.245><>
  DEBUG: ow_regex.c:(100) 1: 0->14 found <><192.168.50.245><>
  DEBUG: ow_parse_address.c:(80) IP <192.168.50.245>
  DEBUG: ow_parse_address.c:(142) First <192.168.50.245>
  DEBUG: ow_net_client.c:(85) Called with [192.168.50.245] IP address=[192.168.50.245] port=[80]
CONNECT: ow_net_client.c:(147) [Host is unreachable] Socket problem
CONNECT: owlib.c:(153) Cannot detect an HA7net server on 192.168.50.245
   CALL: ow_parsename.c:(174) path=[]
  DEBUG: ow_net_client.c:(28) Called with 192.168.50.250 default=80
  DEBUG: ow_regex.c:(53) Not found
  DEBUG: ow_regex.c:(53) Not found
  DEBUG: ow_regex.c:(100) 0: 0->14 found <><192.168.50.250><>
  DEBUG: ow_regex.c:(100) 1: 0->14 found <><192.168.50.250><>
  DEBUG: ow_parse_address.c:(80) IP <192.168.50.250>
  DEBUG: ow_parse_address.c:(142) First <192.168.50.250>
  DEBUG: ow_net_client.c:(85) Called with [192.168.50.250] IP address=[192.168.50.250] port=[80]
CONNECT: ow_net_client.c:(147) [Host is unreachable] Socket problem
CONNECT: owlib.c:(153) Cannot detect an HA7net server on 192.168.50.250
DEFAULT: owlib.c:(52) No valid 1-wire buses found
  DEBUG: ow_exit.c:(17) Exit code = 1
   CALL: ow_lib_close.c:(21) Starting Library cleanup
   CALL: ow_lib_stop.c:(22) Clear Cache
  DEBUG: ow_cache.c:(295) Flipping cache tree (purging timed-out data)
  DEBUG: ow_cache.c:(313) flip cache. tdestroy() will be called.
  DEBUG: ow_cache.c:(295) Flipping cache tree (purging timed-out data)
  DEBUG: ow_cache.c:(313) flip cache. tdestroy() will be called.
   CALL: ow_lib_stop.c:(24) Closing input devices
   CALL: ow_lib_stop.c:(26) Closing output devices
   CALL: ow_lib_close.c:(42) Finished Library cleanup
  DEBUG: ow_lib_close.c:(50) Libraries closed
[15:45:03] INFO: Starting owserver with debug mode...
[15:45:03] NOTICE: Please note that once DEBUG mode is enabled you will not be able to connect to the owserver. Use debug mode only to troubleshoot issues with 1-Wire connectivity!
  DEBUG: ow_inotify.c:(37) Added /etc/owfs.conf to the watch list
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:1) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:2) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:3) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:4) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:5) Program=server, Option=ha7net, Value=192.168.50.250
  DEBUG: ow_opt.c:(342) Configuration file (/etc/owfs.conf:5) Option ha7net recognized as HA7NET. Value=192.168.50.250
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:6) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:7) Program=server, Option=ha7net, Value=192.168.50.245
  DEBUG: ow_opt.c:(342) Configuration file (/etc/owfs.conf:7) Option ha7net recognized as HA7NET. Value=192.168.50.245
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:8) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:9) Program=Not server, Option=server, Value=4304
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:10) Program=server, Option=port, Value=4304
  DEBUG: ow_opt.c:(342) Configuration file (/etc/owfs.conf:10) Option port recognized as port. Value=4304
DEBUG MODE
libow version:
	3.2p4
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:11) Program=http, Option=port, Value=8099
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:12) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:13) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:14) Program=, Option=, Value=
  DEBUG: ow_opt.c:(297) Configuration file (/etc/owfs.conf:15) Program=, Option=Celsius, Value=
  DEBUG: ow_opt.c:(342) Configuration file (/etc/owfs.conf:15) Option Celsius recognized as Celsius. Value=
  DEBUG: ow_daemon.c:(170) main thread id = 140220431973160
   CALL: ow_parsename.c:(174) path=[]
  DEBUG: owlib.c:(77) Global temp limit 0C to 100C (for fake and mock adapters)
   CALL: ow_parsename.c:(174) path=[]
  DEBUG: ow_net_client.c:(28) Called with 192.168.50.245 default=80
  DEBUG: ow_regex.c:(24) Reg Ex expression <^$> compiled to 0x7f879cff8b60
  DEBUG: ow_regex.c:(24) Reg Ex expression <^all$> compiled to 0x7f879cff8b20
  DEBUG: ow_regex.c:(24) Reg Ex expression <^scan$> compiled to 0x7f879cff8ae0
  DEBUG: ow_regex.c:(24) Reg Ex expression <^\*$> compiled to 0x7f879cff8aa0
  DEBUG: ow_regex.c:(24) Reg Ex expression <^[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}$> compiled to 0x7f879cff8a60
  DEBUG: ow_regex.c:(24) Reg Ex expression <^-?[[:digit:]]+$> compiled to 0x7f879cff8a20
  DEBUG: ow_regex.c:(24) Reg Ex expression <^ *([^ ]+)[ 
]*$> compiled to 0x7f879cff89e0
  DEBUG: ow_regex.c:(24) Reg Ex expression <^ *([^ ]+) *: *([^ ]+)[ 
]*$> compiled to 0x7f879cff89a0
  DEBUG: ow_regex.c:(24) Reg Ex expression <^ *([^ ]+) *: *([^ ]+) *: *([^ ]+)[ 
]*$> compiled to 0x7f879cff8960
  DEBUG: ow_regex.c:(53) Not found
  DEBUG: ow_regex.c:(53) Not found
  DEBUG: ow_regex.c:(100) 0: 0->14 found <><192.168.50.245><>
  DEBUG: ow_regex.c:(100) 1: 0->14 found <><192.168.50.245><>
  DEBUG: ow_parse_address.c:(80) IP <192.168.50.245>
  DEBUG: ow_parse_address.c:(142) First <192.168.50.245>
  DEBUG: ow_net_client.c:(85) Called with [192.168.50.245] IP address=[192.168.50.245] port=[80]
CONNECT: ow_net_client.c:(147) [Host is unreachable] Socket problem
CONNECT: owlib.c:(153) Cannot detect an HA7net server on 192.168.50.245
   CALL: ow_parsename.c:(174) path=[]
  DEBUG: ow_net_client.c:(28) Called with 192.168.50.250 default=80
  DEBUG: ow_regex.c:(53) Not found
  DEBUG: ow_regex.c:(53) Not found
  DEBUG: ow_regex.c:(100) 0: 0->14 found <><192.168.50.250><>
  DEBUG: ow_regex.c:(100) 1: 0->14 found <><192.168.50.250><>
  DEBUG: ow_parse_address.c:(80) IP <192.168.50.250>
  DEBUG: ow_parse_address.c:(142) First <192.168.50.250>
  DEBUG: ow_net_client.c:(85) Called with [192.168.50.250] IP address=[192.168.50.250] port=[80]``

**Comment by dim6003** [comment]
And conf file:
```
devices:
  - device_type: ha7net
    ha7net_server: 192.168.50.250
  - device_type: ha7net
    ha7net_server: 192.168.50.245
owhttpd: true
temperature_scale: Celsius
debug: true
```
`

**Comment by dim6003** [comment]
Oups, sorry forget the log above, Just seen error in ip adresses in configuration.yaml above. should be 192.168.0.* instead of 50. Seems better.
After deactivation of debug, looks ok, can see 40 items in the web UI, each Ha7Net owning 20 of them.
Sorry for the trouble.

**Comment by lrybak** [comment]
What about Homeassistant? Are sensors fetched by HA integration?

**Comment by lrybak** [comment]
@ArtGudvin are you able to verify the same?

**Comment by dim6003** [comment]
just trying to add 1-wire integration : has fetched 38 out of 40 items right now. 


De: "softpano" ***@***.***> 
À: "lrybak/hassio-owserver" ***@***.***> 
Cc: "dm martin" ***@***.***>, "Mention" ***@***.***> 
Envoyé: Mardi 29 Octobre 2024 17:55:20 
Objet: Re: [lrybak/hassio-owserver] owserver for two USB DS9490 devices (Issue #22) 





What about Homeassistant? Are sensors fetched by HA integration?

**Comment by dim6003** [comment]
ok, the 2 missing are family 27 / DS2417 / "RTC with interrupt", built-in each HA7Net. certainly filtered by the 1-wire integration, not useful to me anyway.

**Comment by lrybak** [comment]
Looks DS2417 is not supported by HA anyway

**Comment by szczukot** [comment]
@lrybak can You bump version of addon? 
0.4.1 - multiple devices.

**Comment by lrybak** [comment]
What do you mean? The multi device change is so far available in edge channel only. Please check current discussion for details

**Comment by szczukot** [comment]
Aaa, ok.
I'm waiting for it to appear in the stable version of the add-on.

**Comment by lrybak** [comment]
Please do some test on edge before and raise your thoughts. I have just one device and have limited possibility of testing it.

**Comment by szczukot** [comment]
Works for me

`- device_type: serial
  device: >-
    /dev/serial/by-id/usb-MERA-PROJEKT_USB__-__1Wire__MP00206__MPWAMP8Q-if00-port0
- device_type: serial
  device: >-
    /dev/serial/by-id/usb-MERA-PROJEKT_USB__-__1Wire__MP00206__MP2G20C8-if00-port0`

`[12:33:14] INFO: # owserver configuration 

## device(s)
### serial
server: device = /dev/ttyUSB1
### serial
server: device = /dev/ttyUSB2`

![image](https://github.com/user-attachments/assets/a6e54448-fb52-40cb-97e9-621aca5893f9)

**Comment by lrybak** [comment]
Nice, I will make release this weekend

**Comment by lrybak** [comment]
New stable version covering that feature 0.5.0 is released

**Comment by szczukot** [comment]
One more question by the way. Now that I had a window that there was an update, I could enter the configuration there, which is no longer visible after the update - there is nowhere to enter. It looked the same as the settings of other integrations. I could add diagnostic entities there, etc. How can I enter there??

![image](https://github.com/user-attachments/assets/a9f82288-5299-4ade-94e0-a763eebae8a6)

**Comment by szczukot** [comment]
I found it in history.
But how can i enter on this page?
![image](https://github.com/user-attachments/assets/d9828943-65cb-40b0-b9bb-dd31ceb18057)

**Comment by szczukot** [comment]
I know ;)
From devices -> HA Supervisors - >Services.
