### ISSUE TITLE
it works but cant connect to owserver with 1-wire integration

### ISSUE THREAD

**Issue by pumpan** [lrybak/hassio-owserver#24]
seems to me that owserver is running and all my sensor is there but i cant connect to it with the 1-wire integration. isnt it the hostname i should use to connect? 

<img width="329" alt="hostname" src="https://github.com/user-attachments/assets/b6910b29-f047-458a-85d6-f920326d7be9">
<img width="263" alt="sensors" src="https://github.com/user-attachments/assets/63550656-f9d8-41d7-beb0-061c819d57ad">
<img width="291" alt="unknown error" src="https://github.com/user-attachments/assets/920d5873-958e-48a8-be3e-89d21466e5d6">

logs

> -- OneWireQuery done
  DEBUG: read.c:(88) ReadHandler: FS_read_postparse ok size=2
  DEBUG: read.c:(99) ReadHandler: To Client cm->payload=2 cm->size=2 cm->offset=0
Byte buffer Data returned to client, length=2
-- NULL buffer
  DEBUG: data.c:(146) Read message done value=0x7f8730eca0
  DEBUG: ow_parsename.c:(133) /28.12F38A090000/tempres
  DEBUG: data.c:(193) DataHandler: FS_ParsedName_destroy done
  DEBUG: data.c:(207) DataHandler: cm.ret=2
  DEBUG: to_client.c:(74) payload=2 size=2, ret=2, sg=0x144 offset=0 
  DEBUG: data.c:(226) Finished with client request
  DEBUG: handler.c:(131) OWSERVER tcp connection persistence -- reusing connection now.
  DEBUG: ow_tcp_read.c:(63) attempt 24 bytes Time: 10.000000 seconds
  DEBUG: ow_tcp_read.c:(113) read: 24 - 24 = 0
  DEBUG: handler.c:(134) OWSERVER handler done
  DEBUG: ow_net_server.c:(259) Normal completion.
  DEBUG: ow_tcp_read.c:(63) attempt 24 bytes Time: 10.000000 seconds
  DEBUG: ow_tcp_read.c:(113) read: 24 - 0 = 24
  DEBUG: from_client.c:(65) FromClient payload=22 size=32 type=2 sg=0x144 offset=0
  DEBUG: from_client.c:(73) FromClient (no servermessage) payload=22 size=32 type=2 controlflags=0x144 offset=0
  DEBUG: ow_tcp_read.c:(63) attempt 22 bytes Time: 10.000000 seconds
  DEBUG: ow_tcp_read.c:(113) read: 22 - 0 = 22
  DEBUG: handler.c:(72) Persistence requested
  DEBUG: handler.c:(152) START handler /28.12F38A090000/type
   CALL: data.c:(103) DataHandler: parse path=/28.12F38A090000/type
  DEBUG: ow_parseobject.c:(163) /28.12F38A090000/type
   CALL: ow_parsename.c:(174) path=[/28.12F38A090000/type]
  DEBUG: ow_regex.c:(53) Not found
  DEBUG: ow_regex.c:(100) 0: 0->15 found <><28.12F38A090000><>
  DEBUG: ow_regex.c:(100) 1: 0->2 found <><28><.12F38A090000>
  DEBUG: ow_regex.c:(100) 2: 3->15 found <28.><12F38A090000><>
  DEBUG: ow_cache.c:(912) Looking for device 28 12 F3 8A 09 00 00 8F
  DEBUG: ow_cache.c:(1070) Search in cache sn 28 12 F3 8A 09 00 00 8F pointer=0x7f87256c9c index=0 size=4
  DEBUG: ow_cache.c:(1086) Value found in cache. Remaining life: 84 seconds.
  DEBUG: ow_presence.c:(75) Found device on bus 0
  DEBUG: ow_regex.c:(53) Not found
   CALL: data.c:(144) Read message
  DEBUG: read.c:(54) ReadHandler start
  DEBUG: read.c:(60) ReadHandler: From Client sm->payload=22 sm->size=32 sm->offset=0
  DEBUG: read.c:(78) ReadHandler: call FS_read_postparse on /28.12F38A090000/type
  DEBUG: ow_read.c:(72) /28.12F38A090000/type
  DEBUG: ow_read.c:(204) /28.12F38A090000/type
  DEBUG: ow_read.c:(238) About to read </28.12F38A090000/type> extension=0 size=32 offset=0
  DEBUG: ow_read.c:(332) file_length=32 offset=0 size=32
Byte buffer OWQ_parse_output_offset_and_size, length=7
--000: 44 53 31 38 42 32 30
   <DS18B20>
  DEBUG: ow_read.c:(620) Read /28.12F38A090000/type Extension 0 Gives result 0
  DEBUG: ow_cache.c:(374) Adding data for /28.12F38A090000/type
  DEBUG: ow_read.c:(253) return=0
OWQ OneWireQuery structure of /28.12F38A090000/type
    OneWireQuery size=32 offset=0, extension=0
Byte buffer OneWireQuery buffer, length=32
--000: 44 53 31 38 42 32 30 00 00 00 00 00 00 00 00 00
--016: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
   <DS18B20.........................>
    Cleanup = 0006    OneWireQuery I=7 U=7 F=3.45846E-323 Y=7 D=Thu Jan  1 01:00:07 1970

--- OneWireQuery done
  DEBUG: ow_read.c:(263) After read is performed (bytes or error 7)
OWQ OneWireQuery structure of /28.12F38A090000/type
    OneWireQuery size=32 offset=0, extension=0
Byte buffer OneWireQuery buffer, length=32
--000: 44 53 31 38 42 32 30 00 00 00 00 00 00 00 00 00
--016: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
   <DS18B20.........................>
    Cleanup = 0006    OneWireQuery I=7 U=7 F=3.45846E-323 Y=7 D=Thu Jan  1 01:00:07 1970

--- OneWireQuery done
  DEBUG: ow_read.c:(226) /28.12F38A090000/type returns 7
  DEBUG: ow_read.c:(103) /28.12F38A090000/type return 7
  DEBUG: read.c:(80) ReadHandler: FS_read_postparse read on /28.12F38A090000/type return = 7
OWQ OneWireQuery structure of /28.12F38A090000/type
    OneWireQuery size=32 offset=0, extension=0
Byte buffer OneWireQuery buffer, length=32
--000: 44 53 31 38 42 32 30 00 00 00 00 00 00 00 00 00
--016: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
   <DS18B20.........................>
    Cleanup = 0006    OneWireQuery I=7 U=7 F=3.45846E-323 Y=7 D=Thu Jan  1 01:00:07 1970

--- OneWireQuery done
  DEBUG: read.c:(88) ReadHandler: FS_read_postparse ok size=7
  DEBUG: read.c:(99) ReadHandler: To Client cm->payload=7 cm->size=7 cm->offset=0
Byte buffer Data returned to client, length=7
-- NULL buffer
  DEBUG: data.c:(146) Read message done value=0x7f872fdf10
  DEBUG: ow_parsename.c:(133) /28.12F38A090000/type
  DEBUG: data.c:(193) DataHandler: FS_ParsedName_destroy done
  DEBUG: data.c:(207) DataHandler: cm.ret=7
  DEBUG: to_client.c:(74) payload=7 size=7, ret=7, sg=0x144 offset=0 
  DEBUG: data.c:(226) Finished with client request
  DEBUG: handler.c:(131) OWSERVER tcp connection persistence -- reusing connection now.
  DEBUG: ow_tcp_read.c:(63) attempt 24 bytes Time: 10.000000 seconds
  DEBUG: ow_tcp_read.c:(113) read: 24 - 24 = 0
  DEBUG: handler.c:(131) OWSERVER tcp connection persistence -- reusing connection now.
  DEBUG: ow_tcp_read.c:(63) attempt 24 bytes Time: 10.000000 seconds
  DEBUG: handler.c:(134) OWSERVER handler done
  DEBUG: ow_tcp_read.c:(113) read: 24 - 24 = 0
  DEBUG: handler.c:(134) OWSERVER handler done
  DEBUG: ow_net_server.c:(259) Normal completion.
  DEBUG: ow_net_server.c:(259) Normal completion.

**Comment by lrybak** [comment]
Have you tried to add integration in HomeAssiatant as mentioned in documentation? https://github.com/lrybak/hassio-owserver/blob/master/DOCS.md#home-assistant-integration

**Comment by pumpan** [comment]
Yes i did it like this.. 
first i copy the hostname
<img width="730" alt="hostname" src="https://github.com/user-attachments/assets/17eff0fb-a7bf-44c8-b2de-e3e4a1abbb2f">
then i try to connect to it with the integreation but then i just get unknown error
<img width="757" alt="unknown error" src="https://github.com/user-attachments/assets/afb2866c-4207-4c57-903f-5853d286d70e">
and this is what happens if i try any other adress (as expected) (localhost just for an example)
<img width="759" alt="somethingelse" src="https://github.com/user-attachments/assets/86f27864-f32a-4af6-a876-109f4a02eb26">fyi it says "could not connect"

**Comment by lrybak** [comment]
I see in the log files that you enabled DEBUG mode. Please note that once DEBUG mode is enabled you will not be able to connect to the owserver. Please disable DEBUG and give a try

**Comment by pumpan** [comment]
That was the problem! Tyvm great addon!
