### ISSUE TITLE
HA Integration cannot connect to owserver - Failed to connect

### ISSUE THREAD

**Issue by krzysztoflew** [lrybak/hassio-owserver#26]
As was using 1-wire integration connecting to external owserver - it was working fine.
Now I'm trying to use owserver on HA.
As per documentation I'm trying to add hub in 1-wire integration but it cannot connect to owserver - "Failed to connect"

Addon page shows Hostname bd5a478a-owserver.
In integration I'm trying to add hub using standard port 4304 using hostnames:
bd5a478a-owserver, localhost, 127.0.0.1, HA ip.

Owserver was reset to default - did not help.
What should be proper hostname used? 

On HA server CLI I was checking docker, but I do not see port assigned for owserver. Is it expected?

➜  / docker ps
CONTAINER ID   IMAGE                                                       COMMAND               CREATED              STATUS                       PORTS                                                                                                                          NAMES
1b1bcf2ae2f0   ghcr.io/lrybak/owserver/amd64:0.3.8                         "/init"               About a minute ago   Up About a minute                                                                                                                                           addon_bd5a478a_owserver
49e0614540fe   ghcr.io/home-assistant/amd64-hassio-observer:2023.06.0      "/usr/bin/observer"   20 minutes ago       Up 20 minutes                0.0.0.0:4357->80/tcp, :::4357->80/tcp                                                                                          hassio_observer
[...]

Owserver with dummy devices seems to work fine - gui is showing 2 dummy devices:
28.001667239482 | 28.001667239482 | directory
05.DABCEC3453FF | 05.DABCEC3453FF | directory

Core 2024.10.1
Supervisor 2024.09.1
Operating System 13.1
Frontend 20241002.2
Owserver version: 0.3.8

**Comment by lrybak** [comment]
Hi @krzysztoflew, 
The hostname shown on addon info page is correct: bd5a478a-owserver
Regarding ports. It's fine addon does not expose port to the host.

Are you using debug mode? If so you will not be able to connect to owserver. Please use debug only to troubleshoot issues related with 1wire connectivity. For normal operation please disable it

**Comment by krzysztoflew** [comment]
Hi @lrybak,
That was it. Thank you.

**Comment by lrybak** [comment]
I have updated DOCS to reflect that, you're not the first person struggling with that
