### ISSUE TITLE
Setup in HAos for (2) HA7net device(s)

### ISSUE THREAD

**Issue by dim6003** [lrybak/hassio-owserver#28]
Hi,

New to HA, willing to reuse existing hardware, including (2) 1wire network(s), managed by (2) HA7net devices.
For now, trying to connect only one of these (1 step at a time!).
Installed the HA addon, trying to configure it.
My conf.yaml is currently :
`owhttpd: true
device: owserver
device_type: ha7net
ha7net_server: 192.168.0.250
temperature_scale: Celsius`
but I get the following error message : 
`Échec de l'enregistrement de la configuration du module complémentaire, Device 'owserver' does not exist in owserver (1-wire) (bd5a478a_owserver). Got {'owhttpd': True, 'device': 'owserver', 'device_type': 'ha7net', 'ha7net_server': '192.168.0.250', 'temperature_scale': 'Celsius'}`

If I remove the `device: owserver` part, it complains it is missing...
Any help greatly appreciated!

**Comment by lrybak** [comment]
Glad you solve it!

**Comment by dim6003** [comment]
Well, I didn't solve the 2 clients part 😉
