### ISSUE TITLE
IO error "/"

### ISSUE THREAD

**Issue by szczukot** [lrybak/hassio-owserver#29]
I added hassio-owserwer 0.4.0

![image](https://github.com/user-attachments/assets/ddc95e18-2a52-4e82-9e4c-91cbf3ece2d1)

And i added 1-wire hub.
But i see only error:
![image](https://github.com/user-attachments/assets/d8df5ef0-f75a-4fcf-938e-e85123496414)

**Comment by lrybak** [comment]
Hi, Please share more information about your device and configuration used.

**Comment by szczukot** [comment]
I think we can close the thread. After a clean HA install, 1wire works fine. 
But before it behaved strangely. It worked for a few hours and then this error for a few hours. And so on.
