### ISSUE TITLE
Reading analog inputs of DS 2450

### ISSUE THREAD

**Issue by snorkman88** [lrybak/hassio-owserver#31]
I really like this project, congratulations!

I wanted to know if the OWSERVER can interface with the DS 2450 since I need to read 1 analog sensor and haven't been able to find any info about it.

Thanks for any info in advance :-)

**Comment by lrybak** [comment]
Thanks @snorkman88 
Well I think DS2450 is supported in owfs project but not in the Home Assistant itself: please see https://www.home-assistant.io/integrations/onewire/
