### ISSUE TITLE
Disable show warning about 01.7066B11B0000

### ISSUE THREAD

**Issue by pepsonEL** [lrybak/hassio-owserver#4]
If you can please disable option to show this sensor because it show in HA it as warning:

`Logger: homeassistant.components.onewire.sensor
Source: components/onewire/sensor.py:398
Integration: 1-Wire (documentation, issues)
First occurred: 26 września 2021, 17:13:50 (1 occurrences)
Last logged: 26 września 2021, 17:13:50

Ignoring unknown family (01) of sensor found for device: 01.7066B11B0000`

**Comment by lrybak** [comment]
Nie za bardzo widzę możliwość ignorowania poszczególnych urządzeń lub całej ich rodziny w owfs. Pozstaje zgłoszenie do HA lub zmiana loggera, żeby nie logował warningów w homeassistant.components.onewire.sensor
